In [1]:
import pandas as pd

mal = pd.read_csv('data/user_anime000000000006.csv', sep='\t')

me = mal[mal.user_id=='andreu_vall']

me.head()

,user_id,anime_id,favorite,review_id,review_date,review_num_useful,review_score,review_story_score,review_animation_score,review_sound_score,review_character_score,review_enjoyment_score,score,status,progress,last_interaction_date
30500,andreu_vall,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,completed,26.0,2004-05-11 00:00:00
30501,andreu_vall,10087,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,completed,13.0,2011-12-25 00:00:00
30502,andreu_vall,10162,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,completed,11.0,2011-09-16 00:00:00
30503,andreu_vall,10165,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dropped,1.0,2011-09-25 00:00:00
30504,andreu_vall,10408,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,completed,1.0,2011-09-17 00:00:00

In [2]:
me.shape

(279, 16)

In [12]:
filtered = me.dropna(axis=1, how='all')

In [20]:
filtered.sort_values('last_interaction_date', ascending=False).head(60)

,user_id,anime_id,favorite,score,status,progress,last_interaction_date
30744,andreu_vall,50360,0,NaN,plan_to_watch,0.0,2022-02-26 18:50:00
30725,andreu_vall,48569,0,7.0,on_hold,10.0,2022-02-26 18:50:00
30710,andreu_vall,44961,0,5.0,dropped,5.0,2022-02-26 18:50:00
30728,andreu_vall,48736,0,8.0,watching,7.0,2022-02-26 10:45:00
30545,andreu_vall,21,0,9.0,watching,1011.0,2022-02-25 15:31:00
30732,andreu_vall,49114,0,7.0,watching,7.0,2022-02-25 14:49:00
30682,andreu_vall,40834,1,10.0,watching,19.0,2022-02-25 14:21:00
30727,andreu_vall,48583,0,7.0,watching,7.0,2022-02-23 14:35:00
30733,andreu_vall,49310,0,NaN,plan_to_watch,0.0,2022-02-18 00:00:00
30639,andreu_vall,37987,0,9.0,completed,1.0,2022-02-14 00:27:36
30718,andreu_vall,47778,0,10.0,completed,11.0,2022-02-13 19:32:36
30664,andreu_vall,39741,0,8.0,completed,1.0,2022-02-13 15:57:00
30559,andreu_vall,235,0,8.0,watching,1035.0,2022-02-09 15:18:00
30655,andreu_vall,38992,0,7.0,completed,12.0,2022-02-09 09:42:00
30665,andreu_vall,39764,0,7.0,completed,1.0,2022-02-05 16:18:00
30623,andreu_vall,36098,0,9.0,completed,1.0,2022-02-03 12:58:00
30715,andreu_vall,46102,0,9.0,completed,13.0,2022-02-01 12:10:00
30719,andreu_vall,48414,0,NaN,dropped,2.0,2022-01-23 15:31:00
30724,andreu_vall,48561,0,NaN,plan_to_watch,0.0,2021-12-24 00:00:00
30731,andreu_vall,48926,0,9.0,completed,12.0,2021-12-23 00:00:00
30723,andreu_vall,48556,0,7.0,completed,12.0,2021-12-22 00:00:00
30711,andreu_vall,45576,0,9.0,completed,12.0,2021-12-20 00:00:00
30720,andreu_vall,48483,0,6.0,completed,12.0,2021-12-19 00:00:00
30696,andreu_vall,42544,0,NaN,dropped,1.0,2021-12-19 00:00:00
30729,andreu_vall,48849,0,7.0,completed,12.0,2021-10-01 00:00:00
30691,andreu_vall,41587,0,7.0,completed,25.0,2021-09-25 00:00:00
30685,andreu_vall,40904,0,7.0,completed,12.0,2021-09-25 00:00:00
30716,andreu_vall,46471,0,5.0,completed,12.0,2021-09-19 00:00:00
30695,andreu_vall,42282,0,7.0,completed,12.0,2021-09-18 00:00:00
30706,andreu_vall,43969,0,4.0,dropped,5.0,2021-09-18 00:00:00
30726,andreu_vall,48580,0,9.0,completed,12.0,2021-09-18 00:00:00
30687,andreu_vall,41025,0,9.0,completed,20.0,2021-08-30 00:00:00
30708,andreu_vall,44200,0,NaN,plan_to_watch,0.0,2021-08-06 00:00:00
30707,andreu_vall,44074,0,9.0,completed,11.0,2021-07-09 00:00:00
30698,andreu_vall,42938,0,9.0,completed,13.0,2021-06-29 00:00:00
30686,andreu_vall,40938,0,6.0,completed,13.0,2021-06-28 00:00:00
30689,andreu_vall,41457,0,7.0,completed,11.0,2021-06-20 00:00:00
30714,andreu_vall,46095,0,8.0,completed,13.0,2021-06-19 00:00:00
30697,andreu_vall,42897,0,8.0,completed,13.0,2021-04-04 00:00:00
30648,andreu_vall,38474,0,NaN,on_hold,5.0,2021-04-01 00:00:00
30702,andreu_vall,43299,0,NaN,dropped,2.0,2021-03-31 00:00:00
30670,andreu_vall,40028,0,9.0,completed,16.0,2021-03-29 00:00:00
30678,andreu_vall,40748,1,10.0,completed,24.0,2021-03-27 00:00:00
30666,andreu_vall,39783,0,8.0,completed,12.0,2021-03-26 00:00:00
30663,andreu_vall,39617,0,3.0,completed,11.0,2021-03-26 00:00:00
30684,andreu_vall,40852,0,8.0,completed,11.0,2021-03-25 00:00:00
30693,andreu_vall,42203,0,9.0,completed,12.0,2021-03-24 00:00:00
30659,andreu_vall,39535,0,9.0,completed,11.0,2021-03-22 00:00:00
30680,andreu_vall,40787,0,NaN,plan_to_watch,0.0,2020-12-25 00:00:00
30679,andreu_vall,40776,0,8.0,completed,12.0,2020-12-19 00:00:00
30671,andreu_vall,40052,0,6.0,dropped,11.0,2020-12-17 00:00:00
30674,andreu_vall,40456,0,9.0,completed,1.0,2020-10-16 00:00:00
30662,andreu_vall,39587,0,7.0,completed,13.0,2020-09-30 00:00:00
30683,andreu_vall,40839,0,7.0,completed,12.0,2020-09-26 00:00:00
30660,andreu_vall,39547,0,6.0,completed,12.0,2020-09-25 00:00:00
30673,andreu_vall,40417,0,9.0,completed,25.0,2020-09-22 00:00:00
30677,andreu_vall,40591,0,10.0,completed,12.0,2020-06-27 00:00:00
30650,andreu_vall,38555,0,8.0,completed,12.0,2020-06-21 00:00:00
30647,andreu_vall,38408,0,9.0,completed,25.0,2020-04-04 00:00:00
30654,andreu_vall,38883,0,9.0,completed,13.0,2020-04-04 00:00:00

In [11]:
filtered.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 279 entries, 30500 to 30778
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   user_id                279 non-null    object
 1   anime_id               279 non-null    int64
 2   favorite               279 non-null    int64
 3   score                  188 non-null    float64
 4   status                 279 non-null    object
 5   progress               279 non-null    float64
 6   last_interaction_date  256 non-null    object
dtypes: float64(2), int64(2), object(3)
memory usage: 17.4+ KB